version: "3"
services:
  regtest-0:
    image: kylemanna/bitcoind
    command: bitcoind -regtest -conf=/bitcoin/conf/0.conf
    ports:
      - "19000:18444"
      - "19001:19001"
    volumes:
      - ./conf:/bitcoin/conf
  regtest-1:
    image: kylemanna/bitcoind
    command: bitcoind -regtest -conf=/bitcoin/conf/1.conf
    ports:
      - "19010:18444"
      - "19011:19011"
    volumes:
      - ./conf:/bitcoin/conf
  regtest-2:
    image: kylemanna/bitcoind
    command: bitcoind -regtest -conf=/bitcoin/conf/2.conf
    ports:
      - "19020:18444"
      - "19021:19021"
    volumes:
      - ./conf:/bitcoin/conf
